# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0006_auto_20180419_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ManyToManyField(blank=True, to='ks_crm.Course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
