# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(default='/head_imgs/sample.jpg', upload_to='/head_imgs'),
        ),
    ]
