# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0012_auto_20180424_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ID_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.SmallIntegerField(choices=[('0', '专科'), ('1', '本科')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[('0', '男'), ('1', '女')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.SmallIntegerField(choices=[('1', '大一'), ('2', '大二'), ('3', '大三'), ('4', '大四')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ismakeup',
            field=models.SmallIntegerField(choices=[('0', '是'), ('1', '否')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isteacher',
            field=models.SmallIntegerField(choices=[('0', '是'), ('1', '否')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stu_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
