# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0013_auto_20180723_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='true_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
