# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0014_auto_20180724_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.SmallIntegerField(choices=[('1', '大一'), ('2', '大二'), ('3', '大三'), ('4', '大四')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ks_crm.Role'),
        ),
    ]
