# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_crm', '0015_auto_20180818_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(default='', max_length=32),
        ),
    ]
