# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0003_choicequestion_option_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.SmallIntegerField(choices=[(0, 'single_choice'), (1, 'multiple_choices'), (2, 'true_or_false'), (3, 'gap_filling'), (4, 'essay_question')])),
                ('question_index', models.SmallIntegerField()),
                ('question', models.TextField()),
                ('choices', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField()),
                ('question_score', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='ps_id',
        ),
        migrations.RemoveField(
            model_name='essayquestion',
            name='ps_id',
        ),
        migrations.RemoveField(
            model_name='gapfilling',
            name='ps_id',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='ps_id',
        ),
        migrations.RemoveField(
            model_name='paperstruct',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='answerpaper',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paperstruct',
            name='ps_index',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='paper_topic',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='EssayQuestion',
        ),
        migrations.DeleteModel(
            name='GapFilling',
        ),
        migrations.DeleteModel(
            name='WritingTask',
        ),
        migrations.AddField(
            model_name='questionlib',
            name='ps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.PaperStruct'),
        ),
    ]
