# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0004_auto_20180408_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '试卷科目',
                'verbose_name_plural': '试卷科目',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '试题类型',
                'verbose_name_plural': '试题类型',
            },
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.QuestionType'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.PaperType'),
        ),
    ]
