# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0005_auto_20180410_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlib',
            name='question_type',
        ),
        migrations.AddField(
            model_name='paperstruct',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_system.QuestionType'),
        ),
    ]
