# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0007_auto_20180412_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '试卷模块',
                'verbose_name_plural': '试卷模块',
            },
        ),
        migrations.AddField(
            model_name='testpaper',
            name='paper_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_system.PaperModule'),
        ),
    ]
